[mypy]
python_version = 3.10
strict = False
ignore_missing_imports = True
warn_unused_ignores = False
warn_return_any = False
disallow_untyped_defs = False
check_untyped_defs = True
allow_redefinition = True
implicit_reexport = True

# Módulos a compilar com mypyc
[mypy-poolscript.lexer]
disallow_untyped_defs = True

[mypy-poolscript.parser]
disallow_untyped_defs = False

[mypy-poolscript.interpreter]
disallow_untyped_defs = False
warn_return_any = False
