# -*- coding: utf-8 -*-
"""Especificação dos 55 métodos de string — dados do gerador de doc.

53 vivem no PoolStr do interpretador; `get`/`get_json` são resolvidos por um
caminho próprio dele — a tabela da VM tem os 55 juntos, e este arquivo é a
lista canônica. Cada exemplo roda nos dois motores via test_docs_exemplos.py.
"""

STRMET = {
    # ── caixa ───────────────────────────────────────────────────────────────
    "upper": dict(sig='s.upper()', resumo="Tudo em maiúsculas (unicode: ç→Ç, á→Á).",
        params=[], ret="str", erros=[],
        ex=[('post("ação".upper())', "AÇÃO")], bordas=[]),
    "lower": dict(sig='s.lower()', resumo="Tudo em minúsculas.",
        params=[], ret="str", erros=[],
        ex=[('post("AÇÃO".lower())', "ação")], bordas=[]),
    "title": dict(sig='s.title()', resumo="Primeira letra de cada palavra em maiúscula.",
        params=[], ret="str", erros=[],
        ex=[('post("ola mundo".title())', "Ola Mundo")], bordas=[]),
    "capitalize": dict(sig='s.capitalize()', resumo="Só a primeira letra da string em maiúscula; o resto minúsculo.",
        params=[], ret="str", erros=[],
        ex=[('post("OLA mundo".capitalize())', "Ola mundo")], bordas=[]),
    "swapcase": dict(sig='s.swapcase()', resumo="Inverte a caixa de cada letra.",
        params=[], ret="str", erros=[],
        ex=[('post("AbC".swapcase())', "aBc")], bordas=[]),
    "casefold": dict(sig='s.casefold()', resumo="Minúsculas agressivas para comparação sem caixa.",
        params=[], ret="str", erros=[],
        ex=[('post("Straße".casefold())', "strasse")], bordas=["ß vira ss — mais forte que lower()"]),

    # ── aparar / preencher ──────────────────────────────────────────────────
    "strip": dict(sig='s.strip(chars=Null)', resumo="Remove espaços (ou os chars dados) das duas pontas.",
        params=[("chars", "str", "Null", "conjunto de caracteres a remover")], ret="str", erros=[],
        ex=[('post("  oi  ".strip() + "!")', "oi!"), ('post("xxoixx".strip("x"))', "oi")], bordas=[]),
    "lstrip": dict(sig='s.lstrip(chars=Null)', resumo="Remove da ponta ESQUERDA.",
        params=[("chars", "str", "Null", "")], ret="str", erros=[],
        ex=[('post("  oi".lstrip() + "!")', "oi!")], bordas=[]),
    "rstrip": dict(sig='s.rstrip(chars=Null)', resumo="Remove da ponta DIREITA.",
        params=[("chars", "str", "Null", "")], ret="str", erros=[],
        ex=[('post("oi  ".rstrip() + "!")', "oi!")], bordas=[]),
    "removeprefix": dict(sig='s.removeprefix(p)', resumo="Remove o prefixo exato, se presente.",
        params=[("p", "str", "—", "")], ret="str", erros=[],
        ex=[('post("api_nome".removeprefix("api_"))', "nome")], bordas=["sem o prefixo, devolve a string intacta"]),
    "removesuffix": dict(sig='s.removesuffix(p)', resumo="Remove o sufixo exato, se presente.",
        params=[("p", "str", "—", "")], ret="str", erros=[],
        ex=[('post("nome.txt".removesuffix(".txt"))', "nome")], bordas=[]),
    "ljust": dict(sig='s.ljust(largura, preenchimento=" ")', resumo="Preenche à direita até a largura.",
        params=[("largura", "int", "—", ""), ("preenchimento", "str de 1 char", '" "', "")], ret="str", erros=[],
        ex=[('post("ab".ljust(5, "-"))', "ab---")], bordas=[]),
    "rjust": dict(sig='s.rjust(largura, preenchimento=" ")', resumo="Preenche à esquerda até a largura.",
        params=[("largura", "int", "—", ""), ("preenchimento", "str de 1 char", '" "', "")], ret="str", erros=[],
        ex=[('post("ab".rjust(5, "-"))', "---ab")], bordas=[]),
    "center": dict(sig='s.center(largura, preenchimento=" ")', resumo="Centraliza preenchendo dos dois lados.",
        params=[("largura", "int", "—", ""), ("preenchimento", "str de 1 char", '" "', "")], ret="str", erros=[],
        ex=[('post("ab".center(6, "*"))', "**ab**")], bordas=[]),
    "zfill": dict(sig='s.zfill(largura)', resumo="Preenche com zeros à esquerda, respeitando sinal.",
        params=[("largura", "int", "—", "")], ret="str", erros=[],
        ex=[('post("42".zfill(5), "-7".zfill(4))', "00042 -007")], bordas=[]),
    "expandtabs": dict(sig='s.expandtabs(tabsize=8)', resumo="Troca cada tab por espaços até a próxima parada de tabulação (não por um número fixo de espaços).",
        params=[("tabsize", "int", "8", "largura da coluna de tabulação")], ret="str", erros=[],
        ex=[('post("a\\tbc\\td".expandtabs(4))', "a   bc  d")],
        bordas=["o número de espaços varia com a posição: o tab alinha na próxima parada, não insere `tabsize` espaços fixos"]),

    # ── busca ───────────────────────────────────────────────────────────────
    "startswith": dict(sig='s.startswith(prefixo)', resumo="True se começa com o prefixo.",
        params=[("prefixo", "str", "—", "")], ret="bool", erros=[],
        ex=[('post("poolscript".startswith("pool"))', "True")], bordas=[]),
    "endswith": dict(sig='s.endswith(sufixo)', resumo="True se termina com o sufixo.",
        params=[("sufixo", "str", "—", "")], ret="bool", erros=[],
        ex=[('post("a.ps".endswith(".ps"))', "True")], bordas=[]),
    "contains": dict(sig='s.contains(sub)', resumo="True se contém a substring (extensão da PoolScript).",
        params=[("sub", "str", "—", "")], ret="bool", erros=[],
        ex=[('post("banana".contains("nan"))', "True")], bordas=["`has` é o mesmo teste com outro nome"]),
    "has": dict(sig='s.has(sub)', resumo="Alias de contains — True se a substring aparece.",
        params=[("sub", "str", "—", "")], ret="bool", erros=[],
        ex=[('post("banana".has("xyz"))', "False")], bordas=[]),
    "find": dict(sig='s.find(sub, inicio=0, fim=null)', resumo="Índice da primeira ocorrência, ou -1.",
        params=[("sub", "str", "—", ""),
                ("inicio", "int", "0", "posição (em caracteres) onde começa a procurar; negativo conta do fim"),
                ("fim", "int", "null", "posição onde para (exclusivo); `null` = até o fim")],
        ret="int", erros=[],
        ex=[('post("banana".find("na"), "banana".find("xyz"))', "2 -1"),
            ('post("banana".find("na", 3), "banana".find("na", 0, 3))', "4 -1"),
            ('post("pão de mel".find("o"), "pão de mel".find("e", -3))', "2 8")],
        bordas=["posições são em CARACTERES, não bytes — acento conta como 1 (`\"pão\".find(\"o\")` → 2)",
                "`inicio` além do tamanho devolve -1 (não erra)"]),
    "rfind": dict(sig='s.rfind(sub, inicio=0, fim=null)', resumo="Índice da ÚLTIMA ocorrência, ou -1.",
        params=[("sub", "str", "—", ""),
                ("inicio", "int", "0", "posição (em caracteres) onde a faixa de busca começa"),
                ("fim", "int", "null", "onde a faixa termina (exclusivo); `null` = até o fim")],
        ret="int", erros=[],
        ex=[('post("banana".rfind("na"))', "4"),
            ('post("banana".rfind("na", 0, 4), "banana".rfind("na", 5))', "2 -1")],
        bordas=["a faixa `inicio`/`fim` limita ONDE procurar; a posição devolvida é sempre absoluta (do começo da string)"]),
    "index": dict(sig='s.index(sub, inicio=0, fim=null)', resumo="Como find, mas ERRA quando não acha.",
        params=[("sub", "str", "—", ""),
                ("inicio", "int", "0", "posição (em caracteres) onde começa a procurar"),
                ("fim", "int", "null", "onde para (exclusivo); `null` = até o fim")],
        ret="int",
        erros=[("SomeValueUnexpected", "substring ausente (na faixa dada)")],
        ex=[('post("banana".index("na"))', "2"),
            ('post("banana".index("na", 3))', "4")], bordas=[]),
    "rindex": dict(sig='s.rindex(sub, inicio=0, fim=null)', resumo="Como rfind, mas ERRA quando não acha.",
        params=[("sub", "str", "—", ""),
                ("inicio", "int", "0", "posição (em caracteres) onde a faixa de busca começa"),
                ("fim", "int", "null", "onde a faixa termina (exclusivo); `null` = até o fim")],
        ret="int",
        erros=[("SomeValueUnexpected", "substring ausente (na faixa dada)")],
        ex=[('post("banana".rindex("na"))', "4"),
            ('post("banana".rindex("na", 0, 4))', "2")], bordas=[]),
    "count": dict(sig='s.count(sub, inicio=0, fim=null)', resumo="Quantas ocorrências (sem sobreposição) da substring.",
        params=[("sub", "str", "—", ""),
                ("inicio", "int", "0", "posição (em caracteres) onde começa a contar"),
                ("fim", "int", "null", "onde para (exclusivo); `null` = até o fim")],
        ret="int", erros=[],
        ex=[('post("banana".count("na"))', "2"),
            ('post("banana".count("na", 3), "banana".count("a", 1, 4))', "1 2")],
        bordas=["substring vazia conta `len + 1` (uma \"posição\" entre cada caractere), como no Python"]),
    "len": dict(sig='s.len()', resumo="Tamanho em caracteres — forma de método do builtin len.",
        params=[], ret="int", erros=[],
        ex=[('post("olá".len())', "3")], bordas=["número não tem `.len()` — `(150).len()` é erro"]),

    # ── json embutido ───────────────────────────────────────────────────────
    "get_json": dict(sig='s.get_json()', resumo="Interpreta a string como JSON e devolve o valor.",
        params=[], ret="dict | list | valor",
        erros=[("SomeValueUnexpected", "JSON inválido")],
        ex=[('post("{\\"a\\": 1}".get_json())', "{'a': 1}")],
        bordas=["JSON estrito, como o módulo json"]),
    "get": dict(sig='s.get(chave)', resumo="Interpreta como JSON de objeto e devolve o valor da chave.",
        params=[("chave", "str", "—", "")], ret="valor | Null",
        erros=[("SomeValueUnexpected", "JSON inválido")],
        ex=[('post("{\\"a\\": 1}".get("a"))', "1")], bordas=[]),

    # ── classificação (is*) ─────────────────────────────────────────────────
    "isalpha": dict(sig='s.isalpha()', resumo="True se só tem letras (e não é vazia).",
        params=[], ret="bool", erros=[],
        ex=[('post("abc".isalpha(), "a1".isalpha())', "True False")], bordas=[]),
    "isdigit": dict(sig='s.isdigit()', resumo="True se só tem dígitos.",
        params=[], ret="bool", erros=[],
        ex=[('post("123".isdigit(), "1.5".isdigit())', "True False")],
        bordas=["número também responde: `(150).isdigit()` é True — conversão automática pra string"]),
    "isnumeric": dict(sig='s.isnumeric()', resumo="True se só tem caracteres numéricos.",
        params=[], ret="bool", erros=[],
        ex=[('post("123".isnumeric())', "True")], bordas=[]),
    "isdecimal": dict(sig='s.isdecimal()', resumo="True se só tem dígitos decimais.",
        params=[], ret="bool", erros=[],
        ex=[('post("123".isdecimal())', "True")], bordas=[]),
    "isalnum": dict(sig='s.isalnum()', resumo="True se só tem letras e dígitos.",
        params=[], ret="bool", erros=[],
        ex=[('post("a1".isalnum(), "a 1".isalnum())', "True False")], bordas=[]),
    "isspace": dict(sig='s.isspace()', resumo="True se só tem espaços em branco.",
        params=[], ret="bool", erros=[],
        ex=[('post("  ".isspace())', "True")], bordas=[]),
    "isupper": dict(sig='s.isupper()', resumo="True se as letras são todas maiúsculas.",
        params=[], ret="bool", erros=[],
        ex=[('post("ABC".isupper())', "True")], bordas=[]),
    "islower": dict(sig='s.islower()', resumo="True se as letras são todas minúsculas.",
        params=[], ret="bool", erros=[],
        ex=[('post("abc".islower())', "True")], bordas=[]),
    "isascii": dict(sig='s.isascii()', resumo="True se todos os caracteres são ASCII.",
        params=[], ret="bool", erros=[],
        ex=[('post("abc".isascii(), "ção".isascii())', "True False")], bordas=[]),
    "istitle": dict(sig='s.istitle()', resumo="True se cada palavra começa com maiúscula.",
        params=[], ret="bool", erros=[],
        ex=[('post("Ola Mundo".istitle())', "True")], bordas=[]),
    "isprintable": dict(sig='s.isprintable()', resumo="True se todos os caracteres são imprimíveis.",
        params=[], ret="bool", erros=[],
        ex=[('post("oi".isprintable())', "True")], bordas=[]),
    "isidentifier": dict(sig='s.isidentifier()', resumo="True se a string é um identificador válido.",
        params=[], ret="bool", erros=[],
        ex=[('post("nome_1".isidentifier(), "1a".isidentifier())', "True False")], bordas=[]),

    # ── dividir / juntar ────────────────────────────────────────────────────
    "split": dict(sig='s.split(sep=Null, max=-1)', resumo="Divide em lista; sem separador, divide por espaços.",
        params=[("sep", "str", "Null", "Null = qualquer branco, colapsando"), ("max", "int", "-1", "máximo de divisões")],
        ret="list", erros=[],
        ex=[('post("a,b,c".split(","), " a  b ".split())', "['a', 'b', 'c'] ['a', 'b']")], bordas=[]),
    "rsplit": dict(sig='s.rsplit(sep=Null, max=-1)', resumo="Como split, mas conta as divisões da DIREITA.",
        params=[("sep", "str", "Null", ""), ("max", "int", "-1", "")], ret="list", erros=[],
        ex=[('post("a,b,c".rsplit(",", 1))', "['a,b', 'c']")], bordas=[]),
    "splitlines": dict(sig='s.splitlines()', resumo="Divide por quebras de linha, sem incluí-las.",
        params=[], ret="list", erros=[],
        ex=[('post("a\\nb".splitlines())', "['a', 'b']")], bordas=[]),
    "join": dict(sig='sep.join(lista)', resumo="Junta os itens da lista com o separador.",
        params=[("lista", "list de str", "—", "")], ret="str",
        erros=[("SomeValueUnexpected", "item não-string")],
        ex=[('post("-".join(["a", "b", "c"]))', "a-b-c")], bordas=[]),
    "partition": dict(sig='s.partition(sep)', resumo="Tupla (antes, sep, depois) na PRIMEIRA ocorrência.",
        params=[("sep", "str", "—", "")], ret="tup de 3", erros=[],
        ex=[('post("a-b-c".partition("-"))', "('a', '-', 'b-c')")],
        bordas=["sem o separador: `(s, \"\", \"\")`"]),
    "rpartition": dict(sig='s.rpartition(sep)', resumo="Tupla (antes, sep, depois) na ÚLTIMA ocorrência.",
        params=[("sep", "str", "—", "")], ret="tup de 3", erros=[],
        ex=[('post("a-b-c".rpartition("-"))', "('a-b', '-', 'c')")], bordas=[]),

    # ── substituição / formatação ───────────────────────────────────────────
    "replace": dict(sig='s.replace(velho, novo, count=-1)', resumo="Troca ocorrências; velho pode ser LISTA de alvos.",
        params=[("velho", "str | list", "—", "lista troca cada um pelo mesmo novo"),
                ("novo", "str", "—", ""), ("count", "int", "-1", "máximo de trocas")],
        ret="str", erros=[],
        ex=[('post("banana".replace("na", "NA", 1))', "baNAna"),
            ('post("a-b_c".replace(["-", "_"], "."))', "a.b.c")],
        bordas=["a forma com lista é extensão da PoolScript"]),
    "format": dict(sig='s.format(a, b, ...)', resumo="Preenche {} posicionais e {nome} nomeados.",
        params=[("a, b...", "qualquer", "—", "")], ret="str",
        erros=[("SomeValueUnexpected", "chave/índice ausente")],
        ex=[('post("{} e {}".format(1, "x"))', "1 e x")],
        bordas=["`Null` formata como null, não None"]),
    "format_map": dict(sig='s.format_map(dict)', resumo="Como format, buscando os {nome} num dict.",
        params=[("dict", "dict", "—", "")], ret="str",
        erros=[("SomeValueUnexpected", "chave ausente")],
        ex=[('post("{a}!".format_map({"a": "oi"}))', "oi!")], bordas=[]),
    "maketrans": dict(sig='s.maketrans(de, para)', resumo="Tabela de tradução caractere-a-caractere para translate.",
        params=[("de", "str", "—", ""), ("para", "str", "—", "mesmo tamanho")], ret="dict",
        erros=[("SomeValueUnexpected", "tamanhos diferentes")],
        ex=[('post("abc".translate("abc".maketrans("abc", "xyz")))', "xyz")], bordas=[]),
    "translate": dict(sig='s.translate(tabela)', resumo="Troca caracteres segundo a tabela do maketrans (de→para, caractere a caractere).",
        params=[("tabela", "dict", "—", "resultado de `maketrans(de, para)`")], ret="str", erros=[],
        ex=[('post("hello".translate("l".maketrans("l", "L")))', "heLLo")],
        bordas=["a tabela vem sempre do `maketrans` — não é um dict qualquer montado à mão"]),

    # ── regex embutido ──────────────────────────────────────────────────────
    "match": dict(sig='s.match(padrao)', resumo="True se o padrão casa a string INTEIRA (fullmatch).",
        params=[("padrao", "str regex", "—", "")], ret="bool",
        erros=[("SomeValueUnexpected", "padrão inválido")],
        ex=[('post("a1".match("[a-z][0-9]"), "a1b".match("[a-z][0-9]"))', "True False")],
        bordas=["é fullmatch: o padrão tem que cobrir a string toda — pra achar num pedaço use findall"]),
    "findall": dict(sig='s.findall(padrao)', resumo="Lista com todas as ocorrências do padrão.",
        params=[("padrao", "str regex", "—", "")], ret="list",
        erros=[("SomeValueUnexpected", "padrão inválido")],
        ex=[('post("a1b2".findall("[0-9]"))', "['1', '2']")], bordas=[]),
    "sub": dict(sig='s.sub(padrao, novo)', resumo="Substitui as ocorrências do padrão regex.",
        params=[("padrao", "str regex", "—", ""), ("novo", "str", "—", "")], ret="str",
        erros=[("SomeValueUnexpected", "padrão inválido")],
        ex=[('post("a1b2".sub("[0-9]", "#"))', "a#b#")], bordas=[]),

    # ── bytes ───────────────────────────────────────────────────────────────
    "encode": dict(sig='s.encode(encoding="utf-8")', resumo="Converte a string para bytes.",
        params=[("encoding", "str", '"utf-8"', "aceito e ignorado — tudo é utf-8")], ret="bytes",
        erros=[],
        ex=[('post("ab".encode())', "b'ab'")],
        bordas=["bytes só é igual a bytes: `\"ab\" == \"ab\".encode()` é False"]),
}
