# -*- coding: utf-8 -*-
"""Especificação dos 35 builtins — dados do gerador de doc (gera_doc.py).

A fonte da VERDADE é o interpretador; cada exemplo daqui é executado nos dois
motores pelo tests/test_docs_exemplos.py — doc errada QUEBRA a suíte.

Formato: nome -> dict(sig, resumo, params=[(nome, tipo, default, nota)],
ret, erros=[(Tipo, quando)], ex=[(codigo, saida)], bordas=[...]).
"""

BUILTINS = {
    "post": dict(
        sig='post(v1, v2, ...)',
        resumo="Imprime os valores no stdout, separados por espaço, com quebra de linha no final.",
        params=[("v...", "qualquer", "—", "zero ou mais valores")],
        ret="Null",
        erros=[],
        ex=[('post(1, "a", true)', "1 a True"),
            ('post([1, Null], {"k": 2})', "[1, null] {'k': 2}")],
        bordas=["`post()` sem argumento nenhum não imprime nada — nem a quebra de linha; linha em branco é `post(\"\")`",
                "`Null` imprime `null`, inclusive aninhado (`[Null]` → `[null]`)"],
    ),
    "len": dict(
        sig="len(x)",
        resumo="Tamanho de string (em caracteres), lista, tupla, dict ou bytes.",
        params=[("x", "str | list | tup | dict | bytes", "—", "")],
        ret="int",
        erros=[("SomeValueUnexpected", "tipo sem tamanho (int, float, bool, Null)")],
        ex=[('post(len("olá"), len([1, 2]), len({"a": 1}))', "3 2 1")],
        bordas=["string conta CARACTERES unicode, não bytes — `len(\"ç\")` é 1"],
    ),
    "str": dict(
        sig="str(x)",
        resumo="Converte qualquer valor para texto, na renderização da PoolScript.",
        params=[("x", "qualquer", "—", "")],
        ret="str",
        erros=[],
        ex=[('post(str(12) + "!", str(Null), str(true))', "12! null True")],
        bordas=["`str(Null)` é `\"null\"` (nunca `None`); bool vira `True`/`False`"],
    ),
    "int": dict(
        sig="int(x)",
        resumo="Converte para inteiro: string numérica, float (trunca) ou bool.",
        params=[("x", "str | flo | bool | int", "—", "")],
        ret="int",
        erros=[("SomeValueUnexpected", "string que não é número")],
        ex=[('post(int("7"), int(3.9), int(true))', "7 3 1")],
        bordas=["float TRUNCA em direção ao zero (`int(3.9)` → 3), não arredonda"],
    ),
    "flo": dict(
        sig="flo(x)",
        resumo="Converte para número de ponto flutuante.",
        params=[("x", "str | int | bool | flo", "—", "")],
        ret="flo",
        erros=[("SomeValueUnexpected", "string que não é número")],
        ex=[('post(flo("2.5"), flo(3))', "2.5 3.0")],
        bordas=["o nome é `flo`, não `float` — `float` não existe na linguagem"],
    ),
    "bool": dict(
        sig="bool(x)",
        resumo="Verdade do valor: vazio/zero/Null são falsos, o resto é verdadeiro.",
        params=[("x", "qualquer", "—", "")],
        ret="bool",
        erros=[],
        ex=[('post(bool(0), bool(""), bool([1]), bool(Null))', "False False True False")],
        bordas=[],
    ),
    "type": dict(
        sig="type(x)",
        resumo="Nome do tipo do valor, como string.",
        params=[("x", "qualquer", "—", "")],
        ret="str",
        erros=[],
        ex=[('post(type(1), type("a"), type([1]), type(Null))', "int str list Null")],
        bordas=["igual ao método universal `x.type()` — os dois respondem o mesmo nome"],
    ),
    "abs": dict(
        sig="abs(n)",
        resumo="Valor absoluto de um número.",
        params=[("n", "int | flo | bool", "—", "")],
        ret="int | flo",
        erros=[("SomeValueUnexpected", "não-número")],
        ex=[('post(abs(0 - 4), abs(2.5))', "4 2.5")],
        bordas=[],
    ),
    "round": dict(
        sig="round(n, casas=0)",
        resumo="Arredonda um número, opcionalmente com casas decimais.",
        params=[("n", "int | flo", "—", ""), ("casas", "int", "0", "")],
        ret="int | flo",
        erros=[("SomeValueUnexpected", "não-número")],
        ex=[('post(round(3.567, 2), round(2.5))', "3.57 2")],
        bordas=["arredondamento de banco (half-to-even): `round(2.5)` → 2, como no Python"],
    ),
    "hex": dict(
        sig="hex(n)",
        resumo="Inteiro em hexadecimal, com prefixo 0x.",
        params=[("n", "int", "—", "")],
        ret="str",
        erros=[("SomeValueUnexpected", "não-inteiro")],
        ex=[('post(hex(255))', "0xff")],
        bordas=[],
    ),
    "bin": dict(
        sig="bin(n)",
        resumo="Inteiro em binário, com prefixo 0b.",
        params=[("n", "int", "—", "")],
        ret="str",
        erros=[("SomeValueUnexpected", "não-inteiro")],
        ex=[('post(bin(5))', "0b101")],
        bordas=[],
    ),
    "oct": dict(
        sig="oct(n)",
        resumo="Inteiro em octal, com prefixo 0o.",
        params=[("n", "int", "—", "")],
        ret="str",
        erros=[("SomeValueUnexpected", "não-inteiro")],
        ex=[('post(oct(8))', "0o10")],
        bordas=[],
    ),
    "ord": dict(
        sig="ord(c)",
        resumo="Codepoint unicode de um caractere.",
        params=[("c", "str de 1 caractere", "—", "")],
        ret="int",
        erros=[("SomeValueUnexpected", "string com tamanho diferente de 1")],
        ex=[('post(ord("A"))', "65")],
        bordas=[],
    ),
    "chr": dict(
        sig="chr(n)",
        resumo="Caractere do codepoint unicode.",
        params=[("n", "int", "—", "")],
        ret="str",
        erros=[("SomeValueUnexpected", "fora da faixa unicode")],
        ex=[('post(chr(66), chr(231))', "B ç")],
        bordas=[],
    ),
    "range": dict(
        sig="range(fim) | range(inicio, fim, passo=1)",
        resumo="Lista de inteiros de inicio (inclusive) a fim (exclusive).",
        params=[("inicio", "int", "0", ""), ("fim", "int", "—", "exclusive"),
                ("passo", "int", "1", "")],
        ret="list",
        erros=[("SomeValueUnexpected", "argumento não-inteiro")],
        ex=[('post(range(3), range(1, 7, 2))', "[0, 1, 2] [1, 3, 5]")],
        bordas=["devolve LISTA concreta, não um iterador preguiçoso"],
    ),
    "list": dict(
        sig="list(x)",
        resumo="Converte para lista: string vira caracteres, dict vira chaves, tupla vira lista.",
        params=[("x", "str | dict | tup | list", "—", "")],
        ret="list",
        erros=[("SomeValueUnexpected", "tipo não-iterável")],
        ex=[('post(list("abc"), list({"a": 1}))', "['a', 'b', 'c'] ['a']")],
        bordas=[],
    ),
    "sum": dict(
        sig="sum(lista)",
        resumo="Soma os números de uma lista.",
        params=[("lista", "list | tup", "—", "")],
        ret="int | flo",
        erros=[("SomeValueUnexpected", "item não-numérico")],
        ex=[('post(sum([1, 2, 3]))', "6")],
        bordas=["lista vazia soma 0"],
    ),
    "min": dict(
        sig="min(lista) | min(a, b, ...)",
        resumo="Menor valor de uma lista ou dos argumentos.",
        params=[("lista | a, b...", "list ou 2+ valores", "—", "")],
        ret="valor",
        erros=[("SomeValueUnexpected", "lista vazia ou tipos não comparáveis")],
        ex=[('post(min([3, 1]), min(5, 2, 8))', "1 2")],
        bordas=[],
    ),
    "max": dict(
        sig="max(lista) | max(a, b, ...)",
        resumo="Maior valor de uma lista ou dos argumentos.",
        params=[("lista | a, b...", "list ou 2+ valores", "—", "")],
        ret="valor",
        erros=[("SomeValueUnexpected", "lista vazia ou tipos não comparáveis")],
        ex=[('post(max([3, 1]), max(2, 9, 4))', "3 9")],
        bordas=[],
    ),
    "sorted": dict(
        sig="sorted(lista)",
        resumo="Nova lista com os itens em ordem crescente; a original não muda.",
        params=[("lista", "list | tup", "—", "")],
        ret="list",
        erros=[("SomeValueUnexpected", "tipos não comparáveis entre si")],
        ex=[('post(sorted([3, 1, 2]))', "[1, 2, 3]")],
        bordas=[],
    ),
    "reversed": dict(
        sig="reversed(lista)",
        resumo="Nova lista com os itens na ordem inversa; a original não muda.",
        params=[("lista", "list | tup", "—", "")],
        ret="list",
        erros=[("SomeValueUnexpected", "tipo não-sequência")],
        ex=[('post(reversed([1, 2, 3]))', "[3, 2, 1]")],
        bordas=[],
    ),
    "enumerate": dict(
        sig="enumerate(lista)",
        resumo="Lista de tuplas (indice, item), começando em 0.",
        params=[("lista", "list | tup | str", "—", "")],
        ret="list de tup",
        erros=[("SomeValueUnexpected", "tipo não-iterável")],
        ex=[('post(enumerate(["a", "b"]))', "[(0, 'a'), (1, 'b')]")],
        bordas=[],
    ),
    "zip": dict(
        sig="zip(a, b, ...)",
        resumo="Lista de tuplas pareando os iteráveis; para no menor.",
        params=[("a, b...", "list | tup", "—", "2+ iteráveis")],
        ret="list de tup",
        erros=[("SomeValueUnexpected", "tipo não-iterável")],
        ex=[('post(zip([1, 2], ["x", "y"]))', "[(1, 'x'), (2, 'y')]")],
        bordas=["comprimentos diferentes truncam no MENOR, sem erro"],
    ),
    "addEnd": dict(
        sig="addEnd(lista, item)",
        resumo="Anexa o item no FIM da lista, mutando a própria lista.",
        params=[("lista", "list", "—", "mutada in-place"), ("item", "qualquer", "—", "")],
        ret="Null",
        erros=[("SomeValueUnexpected", "primeiro argumento não é lista")],
        ex=[('l = [1]\naddEnd(l, 2)\npost(l)', "[1, 2]")],
        bordas=["muta e devolve Null — não encadeia (`addEnd(l,2).x` não existe)"],
    ),
    "addStart": dict(
        sig="addStart(lista, item)",
        resumo="Insere o item no INÍCIO da lista, mutando a própria lista.",
        params=[("lista", "list", "—", "mutada in-place"), ("item", "qualquer", "—", "")],
        ret="Null",
        erros=[("SomeValueUnexpected", "primeiro argumento não é lista")],
        ex=[('l = [1]\naddStart(l, 0)\npost(l)', "[0, 1]")],
        bordas=[],
    ),
    "removeEnd": dict(
        sig="removeEnd(lista)",
        resumo="Remove e devolve o ÚLTIMO item da lista.",
        params=[("lista", "list", "—", "mutada in-place")],
        ret="o item removido",
        erros=[("SomeValueUnexpected", "lista vazia ou não-lista")],
        ex=[('l = [1, 2]\npost(removeEnd(l), l)', "2 [1]")],
        bordas=[],
    ),
    "removeStart": dict(
        sig="removeStart(lista)",
        resumo="Remove e devolve o PRIMEIRO item da lista.",
        params=[("lista", "list", "—", "mutada in-place")],
        ret="o item removido",
        erros=[("SomeValueUnexpected", "lista vazia ou não-lista")],
        ex=[('l = [1, 2]\npost(removeStart(l), l)', "1 [2]")],
        bordas=[],
    ),
    "map": dict(
        sig="map(lista, fn)",
        resumo="Nova lista com fn aplicada a cada item. A LISTA vem primeiro.",
        params=[("lista", "list | tup", "—", ""), ("fn", "action", "—", "recebe 1 argumento")],
        ret="list",
        erros=[("SomeValueUnexpected", "fn não é chamável (ex.: `map(l, str)` — nome nu de tipo não é função)")],
        ex=[('action dobro(x) { return x * 2 }\npost(map([1, 2, 3], dobro))', "[2, 4, 6]")],
        bordas=["a ordem dos argumentos é INVERSA à do Python: lista primeiro, função depois"],
    ),
    "filter": dict(
        sig="filter(lista, fn)",
        resumo="Nova lista só com os itens em que fn devolve verdadeiro. A LISTA vem primeiro.",
        params=[("lista", "list | tup", "—", ""), ("fn", "action", "—", "recebe 1 argumento")],
        ret="list",
        erros=[("SomeValueUnexpected", "fn não é chamável")],
        ex=[('action par(x) { return x % 2 == 0 }\npost(filter([1, 2, 3, 4], par))', "[2, 4]")],
        bordas=[],
    ),
    "open": dict(
        sig='open(caminho, modo="r")',
        resumo="Abre um arquivo e devolve o handle; combine com `using` para fechar sozinho.",
        params=[("caminho", "str", "—", ""), ("modo", "str", '"r"', '"r", "w", "a", "rb", "wb"...')],
        ret="FileHandle (read/write/close)",
        erros=[("IOError", "arquivo inexistente no modo de leitura")],
        ex=[],
        bordas=["`using open(p, \"w\") as f { f.write(\"x\") }` fecha ao sair do bloco",
                "sem `using`, feche com `f.close()` — o GC fecha o que sobrar, mas tarde"],
    ),
    "sleep": dict(
        sig="sleep(segundos)",
        resumo="Pausa a execução pelo tempo dado (aceita fração).",
        params=[("segundos", "int | flo", "—", "")],
        ret="Null",
        erros=[("SomeValueUnexpected", "não-número")],
        ex=[],
        bordas=["é sono do processo — nada a ver com async"],
    ),
    "gather": dict(
        sig="gather(a, b, ...)",
        resumo="Espera vários `async action` de uma vez, **rodando-os concorrentes**, "
               "e devolve os resultados numa lista, na ordem dos argumentos. Argumento "
               "que não é future passa direto. Aceita também uma **lista** de futures "
               "(`gather(fs)`).",
        params=[("a, b...", "future/qualquer", "—",
                 "futures de `async action`; valor comum passa direto")],
        ret="list — os valores resolvidos, na ordem dos argumentos.",
        erros=[],
        ex=[
            ("async action dobro(n):\n    sleep(0.2)\n    return n * 2\n\n"
             "post(gather(dobro(1), dobro(2), dobro(3)))",
             "[2, 4, 6]"),
            ("async action dobro(n):\n    sleep(0.2)\n    return n * 2\n\n"
             "fs = []\nfor each i in range(3):\n    addEnd(fs, dobro(i))\n"
             "post(gather(fs))",
             "[[0, 2, 4]]"),
        ],
        bordas=[
            "Funciona **nos dois motores** (interpretador e VM em C): resolve os "
            "futures rodando as tasks concorrentes. Valor comum (não-future) volta "
            "como está.",
            "`gather(fs)` com uma lista devolve **lista dentro de lista** (um "
            "resultado por argumento; o argumento-lista vira a sub-lista dos seus "
            "valores).",
        ],
    ),
    "input": dict(
        sig="input(prompt=Null)",
        resumo="Lê uma linha do stdin; o prompt opcional é impresso antes, sem quebra.",
        params=[("prompt", "str", "Null", "")],
        ret="str",
        erros=[],
        ex=[],
        bordas=["SEMPRE devolve str — quem quer número converte com `int(x)`",
                "o `\\r\\n` do Windows não entra no texto lido"],
    ),
    "id": dict(
        sig="id(x)",
        resumo="Identidade do valor: endereço para objetos, o próprio conteúdo para imediatos.",
        params=[("x", "qualquer", "—", "")],
        ret="int",
        erros=[],
        ex=[],
        bordas=["dois `5` têm o mesmo id (valor imediato); duas listas iguais têm ids diferentes"],
    ),
    "load": dict(
        sig="load(path=Null)",
        resumo="Carrega variáveis de um arquivo .env para o ambiente — atalho de dotenv.load.",
        params=[("path", "str", "Null", "Null procura o .env por perto")],
        ret="bool",
        erros=[],
        ex=[],
        bordas=["é a MESMA função de `dotenv.load` exposta sem import"],
    ),
}
